In [1]:
import pandas as pd 
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline


In [2]:
file = "adult.data"
dataset = pd.read_csv(file)
dataset.head()

39          State-gov   77516   Bachelors   13        Never-married  \
0  50   Self-emp-not-inc   83311   Bachelors   13   Married-civ-spouse   
1  38            Private  215646     HS-grad    9             Divorced   
2  53            Private  234721        11th    7   Married-civ-spouse   
3  28            Private  338409   Bachelors   13   Married-civ-spouse   
4  37            Private  284582     Masters   14   Married-civ-spouse   

         Adm-clerical   Not-in-family   White     Male   2174   0   40  \
0     Exec-managerial         Husband   White     Male      0   0   13   
1   Handlers-cleaners   Not-in-family   White     Male      0   0   40   
2   Handlers-cleaners         Husband   Black     Male      0   0   40   
3      Prof-specialty            Wife   Black   Female      0   0   40   
4     Exec-managerial            Wife   White   Female      0   0   40   

    United-States   <=50K  
0   United-States   <=50K  
1   United-States   <=50K  
2   United-States   <=50K  
3            Cuba   <=50K  
4   United-States   <=50K

In [3]:
dataset.keys()

Index(['39', ' State-gov', ' 77516', ' Bachelors', ' 13', ' Never-married',
       ' Adm-clerical', ' Not-in-family', ' White', ' Male', ' 2174', ' 0',
       ' 40', ' United-States', ' <=50K'],
      dtype='object')

In [4]:
from sklearn.preprocessing import OrdinalEncoder
ordinal_encoder = OrdinalEncoder()

In [5]:
state_gov = ordinal_encoder.fit_transform(np.array(dataset[' State-gov']).reshape(-1, 1))
adm_clerical = ordinal_encoder.fit_transform(np.array(dataset[' Adm-clerical']).reshape(-1, 1))
not_in_family = ordinal_encoder.fit_transform(np.array(dataset[' Not-in-family']).reshape(-1, 1))
# bachelors = ordinal_encoder.fit_transform(np.array(dataset[' Bachelors']).reshape(-1, 1))
income = ordinal_encoder.fit_transform(np.array(dataset[' <=50K']).reshape(-1, 1))
male = ordinal_encoder.fit_transform(np.array(dataset[' Male']).reshape(-1, 1))
united_States = ordinal_encoder.fit_transform(np.array(dataset[' United-States']).reshape(-1, 1))
white = ordinal_encoder.fit_transform(np.array(dataset[' White']).reshape(-1, 1))
never_married = ordinal_encoder.fit_transform(np.array(dataset[' Never-married']).reshape(-1, 1))


In [6]:
dataset[' <=50K'] = income
dataset[' Adm-clerical'] =  adm_clerical
#dataset[' Bachelors'] = bachelors
dataset[' State-gov'] = state_gov
dataset[' Male'] = male
dataset[' Never-married'] = never_married
dataset[' Not-in-family'] = not_in_family
dataset[' United-States'] = united_States
dataset[' White']  = white


In [7]:
X = dataset.drop(' Bachelors', axis=1)
Y = dataset[' Bachelors']

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

In [9]:
from sklearn.linear_model import SGDClassifier
from sklearn.pipeline import Pipeline 

In [10]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=1/3)

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
sgd_clf = Pipeline([
    ('std_clf', StandardScaler()),
    ('sgd_clf', SGDClassifier(penalty='l2', l1_ratio=0.2, )),
    ])
sgd_clf.fit(X_train, Y_train)
sgd_clf.score(X_test, Y_test)

0.5164916159941035

In [13]:
sgd_clf = Pipeline([
    ('std_clf', StandardScaler()),
    ('sgd_clf', SGDClassifier(penalty='l1', l1_ratio=0.2, )),
    ])
sgd_clf.fit(X_train, Y_train)
sgd_clf.score(X_test, Y_test)

0.4359683066150728

In [14]:
sgd_clf = Pipeline([
    ('std_clf', StandardScaler()),
    ('sgd_clf', SGDClassifier(penalty='l1', l1_ratio=1, )),
    ])
sgd_clf.fit(X_train, Y_train)
sgd_clf.score(X_test, Y_test)

0.46121245623733187

In [15]:
sgd_clf = SGDClassifier(penalty='l1', l1_ratio=1, )
sgd_clf.fit(X_train, Y_train)
sgd_clf.score(X_test, Y_test)

0.2043486272341994

In [18]:
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import VotingClassifier, BaggingClassifier, AdaBoostClassifier

In [20]:
votting_clf = Pipeline([
    ('std_clf', StandardScaler()),
    ("votting_clf", VotingClassifier(estimators=[
        ('sgd', SGDClassifier()),
        ('svc', SVC()),
        ('linearSvc', LinearSVC())

]))
])
votting_clf.fit(X_train, Y_train)

C:\Users\mhose\anaconda3\lib\site-packages\sklearn\svm\_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


Pipeline(steps=[('std_clf', StandardScaler()),
                ('votting_clf',
                 VotingClassifier(estimators=[('sgd', SGDClassifier()),
                                              ('svc', SVC()),
                                              ('linearSvc', LinearSVC())]))])

In [21]:
votting_clf.score(X_test, Y_test)

0.6428966279712548

In [29]:
baggin_clf = Pipeline([
    ('std_clf', StandardScaler()),
    ("votting_clf", BaggingClassifier(base_estimator=SGDClassifier()))
])
baggin_clf.fit(X_train, Y_train)
baggin_clf.score(X_test, Y_test)

0.5344573429150543

In [30]:
baggin_clf = Pipeline([
    ('std_clf', StandardScaler()),
    ("votting_clf", BaggingClassifier(base_estimator=SVC()))
])
baggin_clf.fit(X_train, Y_train)
baggin_clf.score(X_test, Y_test)

0.958909157914133

In [31]:
adob_boost = Pipeline([
    ('std_clf', StandardScaler()),
    ("votting_clf", AdaBoostClassifier())
])
adob_boost.fit(X_train, Y_train)

Pipeline(steps=[('std_clf', StandardScaler()),
                ('votting_clf', AdaBoostClassifier())])

In [32]:
adob_boost.score(X_test, Y_test)

0.6009765984890363

In [33]:
from sklearn.tree import DecisionTreeClassifier, ExtraTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [34]:
decision_clf = DecisionTreeClassifier()
extra_clf = ExtraTreeClassifier()
randf_clf = RandomForestClassifier()

decision_clf.fit(X_train, Y_train)
extra_clf.fit(X_train, Y_train)
randf_clf.fit(X_train, Y_train)

RandomForestClassifier()

In [35]:
decision_clf.score(X_test, Y_test)

1.0

In [36]:
randf_clf.score(X_test, Y_test)

0.9882071125852221

In [37]:
extra_clf.score(X_test, Y_test)

0.8676064123825318

In [39]:
cross_val_score(randf_clf, X, Y, cv=10)

array([0.98986486, 0.99017199, 0.99017199, 0.98894349, 0.98925061,
       0.98863636, 0.98740786, 0.99293612, 0.98955774, 0.98771499])

In [40]:
cross_val_score(extra_clf, X, Y, cv=10)

array([0.72788698, 0.83906634, 0.81818182, 0.89895577, 0.83660934,
       0.85165848, 0.8009828 , 0.90448403, 0.79330467, 0.88114251])

In [41]:
cross_val_score(decision_clf, X, Y, cv=10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])